DROP DATABASE IF EXISTS S203;
CREATE DATABASE S203;
USE S203;

DROP TABLE IF EXISTS RESERVATIONS;
CREATE TABLE RESERVATIONS(
SALLE VARCHAR(10) NOT NULL,
DATE DATE NOT NULL,
HDEBUT INT NOT NULL,
HFIN INT NOT NULL,
PRENOM VARCHAR(25) NOT NULL,
NOM VARCHAR(50) NOT NULL,
MOTIF VARCHAR(200) NOT NULL,
CHECK (HFIN > HDEBUT),
CHECK (PRENOM NOT LIKE ''),
CHECK (NOM NOT LIKE ''),
CHECK (MOTIF NOT LIKE ''));

DELIMITER //
CREATE TRIGGER reservations_before_insert
BEFORE INSERT ON RESERVATIONS
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT * FROM RESERVATIONS
        WHERE SALLE = NEW.SALLE
        AND DATE = NEW.DATE
        AND ((NEW.HDEBUT >= HDEBUT AND NEW.HDEBUT < HFIN) OR (NEW.HFIN > HDEBUT AND NEW.HFIN <= HFIN))
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Réservation incompatible';
    END IF;
END //
DELIMITER ;

DROP USER IF EXISTS 'CLIENT_S203';
CREATE USER 'CLIENT_S203' IDENTIFIED BY '2023*Azerty';
GRANT SELECT, INSERT ON S203.RESERVATIONS TO 'CLIENT_S203';